### ISSUE TITLE
Remove some items from array

### ISSUE THREAD

**Issue by Keeo** [hhff/ember-infinity#42]
I need to remove some items from array (when user deletes post). Is there way how to do it? I used to use this approach https://github.com/emberjs/data/issues/3313 but its not supported anymore. Simply copying items in route to array does not work either.

**Comment by hhff** [comment]
The infinityModel is no different to any other model array.  Deleting a model in the standard ember data way ( post.deleteRecord() / post.destroyRecord() ) should remove it from the infinityModel array.

**Comment by Keeo** [comment]
Yes, but that only works for the initial batch of items in ember 1.13.x. I think the problem is in the way how items are added into model.
```
model.pushObjects(infinityModel.get('content'));
```

**Comment by hhff** [comment]
kk thanks @Keeo - will look into it.  We currently don't support 1.13+ but will very soon.  If you have any idea how to update it to work with 1.13, please hit us with a PR!

**Comment by hhff** [comment]
looks like we can just do something like:

`infinityModel.addObjects` instead

gotta make this backward compatible too

**Comment by chrismllr** [comment]
@hhff I've got this error when trying ```.addObject()``` and ```.unshiftObject()```

```Uncaught TypeError: internalModel.getRecord is not a function```

Were you able to get it to work?

**Comment by Keeo** [comment]
It works with:
```
model.addObjects(infinityModel.get('content'));
```
but when you call _destroyRecord()_ on one of its models it still does not remove them (except first batch).

If you want to add created record there is 'solution' from mentioned issue.

**Comment by chrismllr** [comment]
Interesting. I wonder if a ```store.unloadAll()``` would still work on those records.. probably not!

So the suggestion is to push your initial ```store.find``` into an array, and then from there push to that same array?

**Comment by hhff** [comment]
Hey duders, just letting you know I should find some time to look into this in the coming week

**Comment by hhff** [comment]
I believe this is resolved in current versions, and if not I think we have the right hooks for the developer to override the behavior.  Please let me know if not.
