### ISSUE TITLE
this.refresh()  unbinds Eventhandler

### ISSUE THREAD

**Issue by franklington** [hhff/ember-infinity#78]
I read following Issues #42 #47 #54 #56.
I need filter and search params in the request and my problem is, if I call `this.refresh()` in `queryParamsDidChange()` then i get the following error:

> Uncaught TypeError: scrollable.height is not a function
> _checkIfInView @	infinity-loader.js:48
> ...

This is my code in the Route: 

```javascript
  model: function(params){
    return this.infinityModel("product",params);
  },

  actions:{
    queryParamsDidChange:function(params){
      this.refresh();
    }
}
```

**Comment by mkorfmann** [comment]
Which version of ember-infinity are you using?

**Comment by mkorfmann** [comment]
Should be resolved if your using latest github with 'hhff/ember-infinity'.

How can I be sure? (https://github.com/hhff/ember-infinity/pull/63)[I fixed the error.]

**Comment by hhff** [comment]
hoping to have an npm release with the fix up soon - wanted to get the new ember data stuff in before the release

**Comment by franklington** [comment]
I'm using the latest `0.0.13` and ember-cli 1.13.1.

**Comment by franklington** [comment]
Thank you guys, it works with the new npm release `0.0.14`  :)

**Comment by hhff** [comment]
we GOT U dog @franklington
